### ISSUE TITLE
Order of atoms in ProbabilityDensityAnalysis.to_chgcar (in pathway.py)

### ISSUE THREAD

**Issue by cajfisher** [materialsvirtuallab/pymatgen-analysis-diffusion#125]
Outputting PDA data in chgcar format can give atoms in the wrong order. This function uses the self.structure.symbol_set to extract the element symbols, but these are stored in alphabetical order, which is not necessarily the order of the atom coordinate data (e.g., as read in from an XDATCAR file) or PDA data, resulting in element symbols and PDA data possibly becoming out of sync.

One way to fix this is to use the same method as in pymatgen.core.trajectory to extract the element symbols in correct order, using itertools functionality.

**Comment by DoubleKx** [comment]
I'm also having this same issue. Alternatively you can fix this manually. Check the correct order of the atoms by printing the structure. Then open the CHGCAR.vasp in a text editor and re-order lines 6 and 7 with the elements and corresponding number.

**Comment by shyuep** [comment]
Sorry for the delay. I just pushed a fix.
