### ISSUE TITLE
DistinctPathFinder mislead by __eq__ with long pathway cutoffs

### ISSUE THREAD

**Issue by jacksund** [materialsvirtuallab/pymatgen-analysis-diffusion#141]
Hi all,

I just wanted to point out a logical bug in the MigrationPath.\__eq__ function. When we look at extremely long pathways, there are cases where the isite, msite, and esite are all equivalent, but the paths are not. Yes, the longer path is likely unreasonable, but it can mask the pathway of interest. Here's an example using mp-22526 (LiCoO2):

```
from pymatgen import MPRester
mpr = MPRester(MY_API_KEY)
structure = mpr.get_structure_by_material_id("mp-22526") # LiCoO2

from pymatgen_diffusion.neb.pathfinder import DistinctPathFinder
dpf = DistinctPathFinder(
    structure = structure,
    migrating_specie = 'Li',
    max_path_length = 5, 
    symprec = 0.1,
    perc_mode = None,
    )

paths = dpf.get_paths() # I print out some results of this below
```

Here, paths will identify the following:

```
[Path of 4.9240 A from Li [0.000, 0.000, 0.000] (ind: 0, Wyckoff: 1a) to Li [1.000, -2.000, 1.000] (ind: 0, Wyckoff: 1a),
Path of 4.9927 A from Li [0.000, 0.000, 0.000] (ind: 0, Wyckoff: 1a) to Li [0.000, -1.000, 0.000] (ind: 0, Wyckoff: 1a)]
```

Likewise, if we run the same code with max_path_length = 10 (this a beyond-reasonable cutoff, but I'm just using it to help illustrate the bug) we will obtain the following paths:

```
[Path of 9.4649 A from Li [0.000, 0.000, 0.000] (ind: 0, Wyckoff: 1a) to Li [3.000, -2.000, -2.000] (ind: 0, Wyckoff: 1a),
Path of 9.5722 A from Li [0.000, 0.000, 0.000] (ind: 0, Wyckoff: 1a) to Li [0.000, -1.000, -1.000] (ind: 0, Wyckoff: 1a),
Path of 9.8826 A from Li [0.000, 0.000, 0.000] (ind: 0, Wyckoff: 1a) to Li [3.000, -1.000, -3.000] (ind: 0, Wyckoff: 1a)]
```

This is clearly in error as the original pathways identified at 5Ang are not even seen anymore. I've already gone ahead and implemented the fix and tested it -- you simply add the following lines to pymatgen_diffusion.neb.pathfinder at line 330:

```
# Check that lengths are within 0.0001 Angstroms
if (self.length - other.length) > 1e-4:
     return False
```
https://github.com/materialsvirtuallab/pymatgen-diffusion/blob/16796454f9c548fb67e57977e7c4c6460355c764/pymatgen_diffusion/neb/pathfinder.py#L330

I choose to hardcode a tolerance of 1e-4 rather than a straight comparison (self.length != other.length) because the lengths often give differences of <1e-6 Angstroms in cases that should be identical. I think it would be fix to loosen this tolerance as well -- even if the path comparison passes on this check, it will continue to symmetrical comparison of sites as it currently does. While this adds an extra check to \__eq__, it actually improves the speed of the function! This is because the distance comparison is cheaper than symmetry comparison, which is done as the last step. After the fix, we get the following outputs for the same code used above:

```
# After Fix;  cutoff = 5Ang
# [Path of 2.8429 A from Li [0.000, 0.000, 0.000] (ind: 0, Wyckoff: 1a) to Li [0.000, -1.000, 1.000] (ind: 0, Wyckoff: 1a),
#  Path of 4.9240 A from Li [0.000, 0.000, 0.000] (ind: 0, Wyckoff: 1a) to Li [1.000, -2.000, 1.000] (ind: 0, Wyckoff: 1a),
#  Path of 4.9927 A from Li [0.000, 0.000, 0.000] (ind: 0, Wyckoff: 1a) to Li [0.000, -1.000, 0.000] (ind: 0, Wyckoff: 1a)]

# After Fix; cutoff = 10Ang
# [Path of 2.8429 A from Li [0.000, 0.000, 0.000] (ind: 0, Wyckoff: 1a) to Li [0.000, -1.000, 1.000] (ind: 0, Wyckoff: 1a),
#  Path of 4.9240 A from Li [0.000, 0.000, 0.000] (ind: 0, Wyckoff: 1a) to Li [1.000, -2.000, 1.000] (ind: 0, Wyckoff: 1a),
#  Path of 4.9927 A from Li [0.000, 0.000, 0.000] (ind: 0, Wyckoff: 1a) to Li [0.000, -1.000, 0.000] (ind: 0, Wyckoff: 1a),
#  Path of 5.7454 A from Li [0.000, 0.000, 0.000] (ind: 0, Wyckoff: 1a) to Li [1.000, -1.000, -1.000] (ind: 0, Wyckoff: 1a),
#  Path of 6.4103 A from Li [0.000, 0.000, 0.000] (ind: 0, Wyckoff: 1a) to Li [1.000, 0.000, -2.000] (ind: 0, Wyckoff: 1a),
#  Path of 7.5216 A from Li [0.000, 0.000, 0.000] (ind: 0, Wyckoff: 1a) to Li [2.000, -3.000, 1.000] (ind: 0, Wyckoff: 1a),
#  Path of 7.5667 A from Li [0.000, 0.000, 0.000] (ind: 0, Wyckoff: 1a) to Li [2.000, -1.000, -2.000] (ind: 0, Wyckoff: 1a),
#  Path of 8.5685 A from Li [0.000, 0.000, 0.000] (ind: 0, Wyckoff: 1a) to Li [2.000, 0.000, -3.000] (ind: 0, Wyckoff: 1a),
#  Path of 9.4649 A from Li [0.000, 0.000, 0.000] (ind: 0, Wyckoff: 1a) to Li [3.000, -2.000, -2.000] (ind: 0, Wyckoff: 1a),
#  Path of 9.5722 A from Li [0.000, 0.000, 0.000] (ind: 0, Wyckoff: 1a) to Li [0.000, -1.000, -1.000] (ind: 0, Wyckoff: 1a),
#  Path of 9.8826 A from Li [0.000, 0.000, 0.000] (ind: 0, Wyckoff: 1a) to Li [3.000, -1.000, -3.000] (ind: 0, Wyckoff: 1a)]
```

Let me know if you think there's a mistake in my breakdown. Otherwise, if you could add these two lines and release a new version, it would be greatly appreciated! Thanks in advance.

-Jack

**Comment by jacksund** [comment]
Just like the issue with the MigrationPath.eq, I believe there is an analogous issue with the MigrationPath.hash as well. Currently its hash is only based on the sum of iindex and eindex for a given pathway, which isn't always unique across different pathways:
https://github.com/materialsvirtuallab/pymatgen-diffusion/blob/16796454f9c548fb67e57977e7c4c6460355c764/pymatgen_diffusion/neb/pathfinder.py#L322

We could instead add more detailed to the hash function by replacing it with...
`return hash((self.iindex, self.eindex, round(self.length,4)))`

I'm still not certain this is as robust as we need it to be, but it definitely solves the few cases I'm looking at and seeing a logical error. Thoughts on this?

**Comment by shyuep** [comment]
Thanks! Yes indeed there can be instances in long paths that the equivalence is not maintained. The general idea has always been to find short "atomic" pathways in the system. I think your solution fixes your use case, but I want to give this a bit more thought. The most robust way of course is to generate a series of images (say 5 or even 10 images) and ensure that the images all map to each other to ensure path equivalence. The problem is of course mapping is costly.

**Comment by jacksund** [comment]
Thanks for the quick reply! If it helps your thinking at all, I was considering pymatgen's [StructureGraph](https://pymatgen.org/pymatgen.analysis.graphs.html#module-pymatgen.analysis.graphs) classes as another way to compare pathway equivalency (for linear interpolated paths at least). Specifically, it may be useful to think of a MigrationPath as an edge, wherein jimage could be utilized. Just some extra food for thought.

**Comment by shyuep** [comment]
I have implemented your partial fix for the length check. AS for the hash, it does not need to be fixed. The reason is because the hash does not need to be unique. The requirement is that items with different hashes MUST be unequal, but non-equal items can have the same hash. E.g., a lazy way of implementing hash functions is just hash = 42. That just simply means that instead of using the hash to partition the search space, the algorithm needs to go through every single item in a list to perform an eq comparison.

The problem with your suggested hash is that it is technically incorrect. Let's say that I have two pathways that are basically close to equal, i.e., your iindex and eindex are the same and the lengths are within tolerance. But one length is 4.49999999 and the other is 4.500000001 . The former will round to 4 and the latter will round to 5. That results in an unequal hash for objects that are equal.

**Comment by jacksund** [comment]
Ah gotcha. I didn't realize two unequal objects were allowed to have the same hash. This is the first time I've ever worked with a custom hash, so thank you for clearing that up. And thanks for pointing that rounding issue out in the hash I suggested!
