### ISSUE TITLE
Finite rounding in endpoint structure creation

### ISSUE THREAD

**Issue by jacksund** [materialsvirtuallab/pymatgen-analysis-diffusion#296]
Would it be possible to increase the tolerance when deleting atoms for start/end structures?

https://github.com/materialsvirtuallab/pymatgen-analysis-diffusion/blob/fddb01992bc8288cdbaba77b3b064b106a1cd274/pymatgen/analysis/diffusion/utils/supercells.py#L155

I have a database setup where I'm initializing `MigrationHop` objects from past data -- so this tolerance is too strict compared to what I'm storing metadata at. When I switch the tolerance from `1e-8` to `1e-5` everything works though. I don't think anyone would need a tolerance lower than a `1e-3` (unless someone is using a physically unreasonable structure). Would it be okay if I opened a pull request for this?

**Comment by shyuep** [comment]
Sure, you can add a kwarg to allow that tolerance to be specified. Then submit a PR.
