### ISSUE TITLE
How to obtain the .npy file or .json file 

### ISSUE THREAD

**Issue by Joey-zhangcy** [materialsvirtuallab/pymatgen-analysis-diffusion#303]
Dear Developers,

Thanks for your work, i'm so interested in the the  probability_analysis.ipynb. I want to ask a simple question that how could we get the .npy file on our work for generating the .vasp file .By vasp or some other code?could you tell me some details about it?

Thanks for your help in advance,
Regards,
Joey

**Comment by shyuep** [comment]
You should use the second example. The diffusion analyzer converts VASP calculation files to the correct format for the probability density analysis.
