### ISSUE TITLE
how to obtain the .npy and .json file

### ISSUE THREAD

**Issue by Joey-zhangcy** [materialsvirtuallab/pymatgen-analysis-diffusion#304]
Dear Developers,
Thanks for your contribution for the pymatgen, I am interested in the probability_analysis.ipynb,I thought it is fantacy. But i don't know how to generate the  .npy or the .json file of our own work. By vasp or some other code ?.Could you give me some advice?

Thanks for your help in advance,
Regards,
Joey

**Comment by qiujinkai1** [comment]
Hello, have you solved this problem? I meet the same problem that how to get the .json file from vasp output trajectory files. Could you give me some suggestions? Thank you very much
