### ISSUE TITLE
Error with get_arrhenius_plot

### ISSUE THREAD

**Issue by thienbinh92** [materialsvirtuallab/pymatgen-analysis-diffusion#306]
I am trying an example and plot with `get_arrhenius_plot` function. No error, but figure does not show information.
`temperatures = [600, 800, 1000, 1200]`
`analyzers = collections.OrderedDict()`
`for temp in temperatures:`
`    with open("aimd_data/%d.json" % temp) as f:`
`        d = json.load(f)`
`        analyzers[temp] = DiffusionAnalyzer.from_dict(d)`
`diffusivities = [d.diffusivity for d in analyzers.values()]`
`#print(temperatures, diffusivities)`
`plt = get_arrhenius_plot(temperatures, diffusivities)`
<img width="809" alt="Screenshot 0004-03-25 at 0 41 01" src="https://user-images.githubusercontent.com/56110825/159954804-2064b247-5252-4efa-b380-f1fb8a7c777f.png">

**Comment by shyuep** [comment]
This shouldn't happen, but looking at your axis, your plot was not correctly initiatlized. There are examples at https://matgenb.materialsvirtuallab.org/ you can refer to for such plots.
