### ISSUE TITLE
[Bug]: pretty_plot() gives error due to the breaking change of pymatgen

### ISSUE THREAD

**Issue by goodwilling** [materialsvirtuallab/pymatgen-analysis-diffusion#363]
### Version

v2023.8.15

### Which OS(es) are you using?

- [ ] MacOS
- [X] Windows
- [ ] Linux

### What happened?

Due to the breaking change of pymatgen (Breaking: Have plot methods return plt.Axes object, not matplotlib module), the following error comes out in the current version. 
 
pymatgen\analysis\diffusion\analyzer.py", line 560, in get_msd_plot
    plt = pretty_plot(12, 8, plt=plt)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: pretty_plot() got an unexpected keyword argument 'plt'

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by goodwilling** [comment]
Sorry to open this issue again.  Due to the breaking change of pymatgen (Have plot methods return plt.Axes object, not matplotlib module), the calling of pretty_plot returns Axes instead of matplotlib.pyplot. Therefore, those codes and docs related to the calling of pretty_plot have to be changed accordingly, otherwise error will come out. Thanks.

**Comment by shyuep** [comment]
@janosh Can you fix? I think this change is causing more issues than it is worth.

**Comment by janosh** [comment]
That was always part of the bargain. I'd recommend taking the hit and fixing downstream errors. The API improvements from returning `ax` instead of `plt` are worth quite a lot imo and were a substantial amount of work. This is the 1st issue I've seen about it.

**Comment by shyuep** [comment]
You are hearing about it only from ONE code dependency. There may be a gazillion other dependent code bases and you are expecting everyone to fix this on their end.
