### ISSUE TITLE
[Bug]: Website Access Issue: Materials Virtual Lab pymatgen-diffusion Guide

### ISSUE THREAD

**Issue by LiangWenshuo1118** [materialsvirtuallab/pymatgen-analysis-diffusion#370]
### Email (Optional)

09123790@cumt.edu.cn

### Version

v2023.1.1

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [x] Linux

### What happened?

I'm experiencing an issue accessing the Materials Virtual Lab guide for pymatgen-diffusion at the following URL: [https://guide.materialsvirtuallab.org/pymatgen-diffusion/](https://guide.materialsvirtuallab.org/pymatgen-diffusion/). The website appears to be down or inaccessible.

### Code snippet

```python
1. Navigate to [https://guide.materialsvirtuallab.org/pymatgen-diffusion/](https://guide.materialsvirtuallab.org/pymatgen-diffusion/).
2. Observe the inability to access the site or receive an error message.
```

### Log output

```shell
404 File not found
The site configured at this address does not contain the requested file.
If this is your site, make sure that the filename case matches the URL as well as any file permissions.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shyuep** [comment]
The url is https://materialsvirtuallab.github.io/pymatgen-analysis-diffusion/ .
