### ISSUE TITLE
[Bug]: get_arrhenius_plot() failed

### ISSUE THREAD

**Issue by LiangWenshuo1118** [materialsvirtuallab/pymatgen-analysis-diffusion#375]
### Version

v2023.8.15

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What happened?

I encountered a `TypeError` when trying to use the `get_arrhenius_plot` function from the `pymatgen.analysis.diffusion.analyzer` module.

### Code snippet

```python
https://github.com/materialsvirtuallab/Data-driven-First-Principles-Methods-for-the-Study-and-Design-of-Alkali-Superionic-Conductors/blob/master/notebooks/3%20-%20Diffusivity%20and%20Ionic%20Conductivity.ipynb
```

### Log output

```shell
File "/home/lws/Desktop/SSE/analysis.py", line 22, in <module>
    get_arrhenius_plot(temperatures, diffusivities).savefig("arrhenius_plot.png")
File "/home/lws/anaconda3/envs/deepmd/lib/python3.10/site-packages/pymatgen/analysis/diffusion/analyzer.py", line 1099, in get_arrhenius_plot
    ax = plt.axes()
TypeError: 'Axes' object is not callable
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by okibrisli** [comment]
hello @LiangWenshuo1118 

did you figure out something for this one?

**Comment by okibrisli** [comment]
@shyuep could you please fix this one and van hove analysis too? they have similar issues


thank you in advance

**Comment by shyuep** [comment]
Fixed.
