### ISSUE TITLE
 [Bug]: msd, arrhenius and van hove plotting functions are not working!

### ISSUE THREAD

**Issue by okibrisli** [materialsvirtuallab/pymatgen-analysis-diffusion#391]
### Version

latest

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What happened?

I want to plot arrhenius, msd and van hove plots but all of them return similar error as you can see below. I just downloaded the last commit by @shyuep but nothing changed. Could you please fix the plotting issues in genereal?

Thank you in advance!

### Code snippet

```python
analyzer.get_msd_plot(msd_plot_filename)
```

### Log output

```shell
Traceback (most recent call last):
  File "/gpfs/fs0/scratch/o/ovoznyy/orhan/conductivity_pymatgen/conductivity.py", line 123, in <module>
    analyzer.get_msd_plot(msd_plot_filename)
  File "/gpfs/fs1/home/o/ovoznyy/orhan/general/lib/python3.12/site-packages/pymatgen/analysis/diffusion/analyzer.py", line 547, in get_msd_plot
    plt.xlabel(f"Timestep ({unit})")
    ^^^^^^^^^^
AttributeError: 'Axes' object has no attribute 'xlabel'. Did you mean: '_label'?
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by okibrisli** [comment]
also that would be nice if we could get a new pypi release

**Comment by shyuep** [comment]
Fixed.

**Comment by okibrisli** [comment]
Thank you very much! Is there a new pypi release?
