### ISSUE TITLE
[Bug]: msd, arrhenius and van hove plotting functions are not working again after v2024.6.24 release!

### ISSUE THREAD

**Issue by okibrisli** [materialsvirtuallab/pymatgen-analysis-diffusion#392]
### Email (Optional)

orhankibrisli@gmail.com

### Version

v2024.6.24

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What happened?

I reinstalled pymatgen and pymatgen-diffusion-analysis today but still cannot use plotting functions.

### Code snippet

```python
analyzer.get_msd_plot(msd_plot_filename)
```

### Log output

```shell
Traceback (most recent call last):
  File "/gpfs/fs0/scratch/o/ovoznyy/orhan/conductivity_pymatgen/conductivity.py", line 123, in <module>
    analyzer.get_msd_plot(msd_plot_filename)
  File "/gpfs/fs1/home/o/ovoznyy/orhan/general/lib/python3.12/site-packages/pymatgen/analysis/diffusion/analyzer.py", line 552, in get_msd_plot
    plt.tight_layout()
    ^^^^^^^^^^^^^^^^
AttributeError: 'Axes' object has no attribute 'tight_layout'. Did you mean: '_in_layout'?
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shyuep** [comment]
Sorry I just pushed a fix. With added tests.
