### ISSUE TITLE
[Bug]: v2024.6.25 pypi installation doesn't install analyzer.py and init

### ISSUE THREAD

**Issue by okibrisli** [materialsvirtuallab/pymatgen-analysis-diffusion#395]
### Email (Optional)

orhankibrisli@gmail.com

### Version

v2024.6.25

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What happened?

@shyuep could you please check pypi installer. I downloaded these two files from repo manually and try to run some calcualtions now..

### Code snippet

```python
from pymatgen.analysis.diffusion.analyzer import DiffusionAnalyzer, get_extrapolated_conductivity, \
    get_extrapolated_diffusivity, get_conversion_factor, fit_arrhenius, get_arrhenius_plot
```

### Log output

```shell
Traceback (most recent call last):
  File "/gpfs/fs0/scratch/o/ovoznyy/orhan/conductivity_pymatgen/conductivity.py", line 3, in <module>
    from pymatgen.analysis.diffusion.analyzer import DiffusionAnalyzer, get_extrapolated_conductivity, \
ModuleNotFoundError: No module named 'pymatgen.analysis.diffusion.analyzer'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shyuep** [comment]
My apologies. Turns out there was a bad spec in the toml file. I just released 2024.6.25.1 and tested on a new venv. It should work. Strange that the CI didn't catch this.
