### ISSUE TITLE
Order of atoms in generated path by IDPP solver

### ISSUE THREAD

**Issue by goodwilling** [materialsvirtuallab/pymatgen-analysis-diffusion#72]
Dear Developers, 

Thank you for your interesting work on pymatgen-diffusion. 

In my testing,  I use the following script to generate an initial path of NEB: 

the_solver = IDPPSolver.from_endpoints(endpoints=[init_struct, final_struct], nimages=nimages, 
                                sort_tol=sort_tol)
new_path = the_solver.run(maxiter=5000, tol=1e-5, gtol=1e-3, species=species) 

This functionality is very convenient for me, however, it is found that the order of atoms in the generated path can be different from those in the given end points (initial_struct, final_struct). For example, the order in O, H will be changed into H, O using the IDPP solver. Since we need to fix some substrate layers in some NEB calculations and these "fix" flags have already been set for the initial/final_struct, it is desired that the generated path can use the same atomic order as given in the initial/final_struct.    

Can I easily achieve this by some minor revisions of scripts?  Thank you.

**Comment by Zhuoying** [comment]
@goodwilling 
Thanks for your feedback. One simple solution is you add selective_dynamics to Poscar **after** you generated the NEB inputs. 
In NEB calculations, we need to ensure the mobile species (vacancy or interstitial) are in the same place for each image. An easy way to do this is by moving the hopping atoms to the beginning of structures(that is what our get_endpoints_from_index code did). However, when writing out the inputs, the same species will be put together in your POSCAR to avoid duplicate pseudopotential in POTCAR. 
Hope this could solve your issue. 
If not, pls feel free to send us your structures and we will take a look at it.

**Comment by AnGeLiQuE-LSR** [comment]
Dear Developers,
I want to generate an initial path for Pb diffusion in Fe. I also found that the final structure generated  was different from my input: The position of the Pb atom was swapped with one of the Fe atoms. I tried to remove the tag "selective_dynamics" and the fixed atoms, but it didn't work differently.
Here is my POSCARs,
[POSCAR_i.txt](https://github.com/user-attachments/files/17059314/POSCAR_i.txt)
[POSCAR_f.txt](https://github.com/user-attachments/files/17059312/POSCAR_f.txt)
Can you to help me solve this issue? Thank you
